#!/bin/bash
set -eu # exit script on errors

echo "copy qr-hunt env"
rsync /home/git/www/qr-hunt/.env .

nvm use 22.13.1

echo "> npm install server..."
npm run install-server

# build is done with github actions
# echo "> npm run build..."
# npm run build

export MAIN="server"
