name: Deploy Release
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and cache client dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client

      - name: Build client
        run: npm run build
        working-directory: client
        env:
          VUE_APP_GOOGLE_API_KEY: ${{ secrets.VUE_APP_GOOGLE_API_KEY }}

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: "*/dist"
  deploy:
    needs: build

    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: "master"
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: |
          git remote add server git@zolly.ml:repos/qr-hunt.git
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add */dist -f
          git commit -m "Build files"
          git push -u server master -f
