name: Test Environment - Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  deploy:
    uses: VictorWinberg/raspberry-pi-setup/.github/workflows/preview-deploy.yml@main
    with:
      app: qr-hunt
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      VUE_APP_GOOGLE_API_KEY: ${{ secrets.VUE_APP_GOOGLE_API_KEY }}
