name: Test Environment - Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  deploy:
    uses: VictorWinberg/raspberry-pi-setup/.github/workflows/preview-deploy.yml@main
    with:
      app: qr-hunt
      docker_build_args: |
        VUE_APP_GOOGLE_API_KEY=${{ secrets.VUE_APP_GOOGLE_API_KEY }}
        VUE_APP_VERSION=preview-pr-${{ github.event.pull_request.number }}
    secrets: inherit
