name: Test Environment - Remove

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  remove:
    uses: VictorWinberg/raspberry-pi-setup/.github/workflows/preview-remove.yml@main
    with:
      app: qr-hunt
    secrets: inherit
